### ISSUE TITLE
Close settings button. 👍

### ISSUE THREAD

**Issue by mangrove108** [ismaelestalayo/CryptoTracker#25]
**Is your feature request related to a problem? Please describe:**
Cant close settings menu in app. Have to close the app completely.

**Describe the solution you'd like:**

**Additional context:**

**Comment by ismaelestalayo** [comment]
I can replicate your issue. Indeed the Settings pane used to be closable by cliking outside of the dialog, but it no longer is.

For the meantime, in my end I'm able to close the Settings with the Escape button.
Could you try that workaround while I work on a fix?

**Comment by mangrove108** [comment]
Yes it works. Thanks. Closable Button would be more convenient though. 👍

**Comment by ismaelestalayo** [comment]
Good to know. I've fixed your issue it by revamping the layout of the Settings dialog:

![image](https://user-images.githubusercontent.com/17100634/160215659-16d3ff3b-97e7-47a7-bcd3-2167cb49b4dc.png)


and it will be released on the next update with a couple of bug fixes.

**Comment by mangrove108** [comment]
thanks

**Comment by ismaelestalayo** [comment]
new version 6.2 was just approved on the store, which brings the updates Settings and fixes your issue.
Feel free to open more issues for any other bug or feature request
