### ISSUE TITLE
Specify marketplace commision fee

### ISSUE THREAD

**Issue by OnlyOnePro** [ismaelestalayo/CryptoTracker#27]
**Describe the solution you'd like:**
Add a new field to the coin to specify of the cost of purchase how much of that were commission fees. This could be useful for analytical purposes, and if the [sell feature](https://github.com/ismaelestalayo/CryptoTracker/projects/2#card-68998945) is implemented we could use the app as a ledger more than a on-the-spot tracker (which tbh is pretty cool on its own)
Also depending on a configuration CheckBox on the settings page, this could be ignored by the user as losses from that coin (I know it is dumb but I know some people that would love this)

**Comment by ismaelestalayo** [comment]
I've done a quick test of adding a "Transaction fee" field to purchases, and you can see here how it affects the "Buy price" of the purchase by subtracting the fee from the total cost:

![image](https://user-images.githubusercontent.com/17100634/161447749-f4f5b486-1044-4c68-b268-dfc5886b8487.png)

![image](https://user-images.githubusercontent.com/17100634/161447771-923ce2b0-bc6a-4e60-a255-c3815905b09a.png)


You think there should be a toggle/checkbox in the Settings to set whether the fees should be taken into account to calculate the profit of a purchase?
