### ISSUE TITLE
CoinSuggestion control displays wrong text

### ISSUE THREAD

**Issue by OnlyOnePro** [ismaelestalayo/CryptoTracker#28]
**Describe the bug:**
When selecting a coin under specific conditions, the AutoSuggest component inside the CoinSuggestion custom control would display **UWP.Models.SuggestionCoin** rather than the coin's actual symbol.

**To Reproduce:**
1. Open the Add new Coin popup on the Portfolio page
2. Click on the CoinSuggestion control. Click on the BTC coin.
3. Click again on the CoinSuggestion control and select the BTC again.

Alternative steps:
1. Open the Add new Coin popup on the Portfolio page.
2. Search for UTK
3. Click on the first suggestion (the one that shows the currency's symbol).

**Expected behavior:**
The coin's symbol should be the one being shown on the CoinSuggestion's text.

**Screenshots:**
![image](https://user-images.githubusercontent.com/27441273/161387488-df5ef6f0-aa12-49d2-be36-a80990d59523.png)

**Additional context**
AppVersion as reported on the Microsoft Store: 6.2.0.
A fix has already been completed on my side and a PR will be made to solve this issue.

**Comment by ismaelestalayo** [comment]
I did not catch that bug or know about `UpdateTextOnSelect`.
The PR has just been merged. Thanks!
