### ISSUE TITLE
Feature request - Add the possibility to add a custom line in graphs

### ISSUE THREAD

**Issue by FJduFou** [ismaelestalayo/CryptoTracker#32]
Add a feature for add a custom line the the Home page graph for can see easily a limit that interests us...

**Comment by ismaelestalayo** [comment]
Playing with your suggestion I managed to draw both vertical and horizontal lines, and I though it would be cool to draw lines on the dates where a purchase was made (toggleable with a button).

Next day I'll try to come up with a good way to let users add horizontal lines on set prices. What do you think?

![image](https://user-images.githubusercontent.com/17100634/189546531-49c2032d-2050-4801-8cfc-bdab51df15f5.png)

**Comment by FJduFou** [comment]
Yea good!

**Comment by ismaelestalayo** [comment]
I've finished working on this feature and will upload a new version soon. 

In the new update there are two toggle buttons on the chart's settings (which are saved across all coins), to show vertical and horizontal annotations for purchases and alerts:

![image](https://user-images.githubusercontent.com/17100634/192616540-9a5bfc1f-76e1-44d2-b208-f8f33e8d95a3.png)

**Comment by ismaelestalayo** [comment]
After testing it, I just uploaded the new v6.4.0 update to the store which should go live in a few hours.
Thanks for the feature suggestion!
