### ISSUE TITLE
Issue - COVAL graph broken

### ISSUE THREAD

**Issue by FJduFou** [ismaelestalayo/CryptoTracker#33]
**Describe the bug:**
Graph of COVAL is broken, only for 1h, 4h and 1d

**To Reproduce:**
1. Go to COVAL graph

**Expected behavior:**
Just see a normal graph

**Screenshots:**
![image](https://user-images.githubusercontent.com/46401854/186001867-9136e1d3-6292-4be1-a61b-e1a555821ffe.png)
![image](https://user-images.githubusercontent.com/46401854/186001942-bef8ef93-66ff-4fc4-88e0-b8eeac446dbb.png)
![image](https://user-images.githubusercontent.com/46401854/186001973-ca5add3e-5492-444e-a281-648b0df4d191.png)
![image](https://user-images.githubusercontent.com/46401854/186002013-03fb814f-9151-4f95-b9be-e8b9d80c6f45.png)
![image](https://user-images.githubusercontent.com/46401854/186002079-d6aaa2fe-9cb4-4fa9-b858-f15e580b9617.png)

**Additional context**
None

**Comment by ismaelestalayo** [comment]
I've checked and seems like the API is returning very strange values.

Debugging the app I've seen that for small time spans and for COVAL, the API returns mostly two values of prices which is what makes those weird charts:
![image](https://user-images.githubusercontent.com/17100634/188322337-fc913cb4-f395-43d6-aa7a-742cdfc785aa.png)

All the points in the chart are either 0.0155€ or 0.001983€
![image](https://user-images.githubusercontent.com/17100634/188322411-05b727e3-c62b-44db-bc5e-321979917717.png)
