### ISSUE TITLE
owner

### ISSUE THREAD

**Issue by tl6666** [ismaelestalayo/CryptoTracker#35]
[yarn-error.log](https://github.com/ismaelestalayo/CryptoTracker/files/9401677/yarn-error.log)
**Describe the bug:**

**To Reproduce:**

**Expected behavior:**

**Screenshots:**

**Additional context**

**Comment by ismaelestalayo** [comment]
I'm sorry, what's the issue exactly? and why did you attach a yarn error log?
You need to overwrite the default answers of the issue template

**Comment by FJduFou** [comment]
It's not in the build?

**Comment by ismaelestalayo** [comment]
> > I'm sorry, what's the issue exactly? and why did you attach a yarn error log?
> > You need to overwrite the default answers of the issue template
> 
> It's not in the build?

what do you mean exactky?
That log is not from my app

**Comment by FJduFou** [comment]
> > > I'm sorry, what's the issue exactly? and why did you attach a yarn error log?
> > > You need to overwrite the default answers of the issue template
> > 
> > It's not in the build?
> 
> what do you mean exactky?
> That log is not from my app 
> 

Oh sorry, my bad, I just see e-commerce-with-react... I think you can just close this issue...
