### ISSUE TITLE
Option to add CoinMarketCap as data source

### ISSUE THREAD

**Issue by Novack** [ismaelestalayo/CryptoTracker#43]
Thank you for such a fantastic tool.

Have you considered the possibility of introducing an option to enter an API key for retrieving data from CoinMarketCap.com?
Each user can have a personal key. https://coinmarketcap.com/api/

Cheers, keep up the awesome work.

**Comment by ismaelestalayo** [comment]
Yup, I did consider it at the beggining of the development. However i'm not currently using their API (because of how low their free API limits are). So for the moment this is not needed
