### ISSUE TITLE
Add dynamic hotizontal line to graph

### ISSUE THREAD

**Issue by Novack** [ismaelestalayo/CryptoTracker#44]
The CoinMarketCap dynamic (mouse following) horizontal line is pretty useful, and would be great to have that in CryptoTracker.

![image](https://user-images.githubusercontent.com/1981463/229645024-a1f9c38b-ae60-49d1-9f0e-cafcd97fd249.png)

**Comment by ismaelestalayo** [comment]
Thanks for your suggestion!
I think it did cross my mind to implement that kind of horizontal line. However, I just checked the doc of the charting library used in my app and it only supports vertical lines.

(See https://docs.telerik.com/devtools/universal-windows-platform/controls/radchart/behaviors/charttrackballbehavior)
