### ISSUE TITLE
Add option for vertical axis info in the graph

### ISSUE THREAD

**Issue by Novack** [ismaelestalayo/CryptoTracker#45]
Currently the graphs are great, but often they feel too minimalistic. Sometimes reference data for the vertical axis would greatly improve the value of a quick look at the graphs. Could be added as an option, if the idea is to keep it minimal by default (which sometimes do feel better).

Once more, a good reference for me is coinmarketcap.com

**Comment by ismaelestalayo** [comment]
Thanks for the suggestion Novack.
I'll play around with the idea to see if there's a visually appealing and useful way to implement it:

![image](https://user-images.githubusercontent.com/17100634/231264046-5c2783aa-3eba-431a-ae82-59ea76abafd1.png)

**Comment by ismaelestalayo** [comment]
I released a couple of days ago v6.5 which brings this vertical axis as an optional toggle for the charts (along other fixes), so i'll mark this as done:

![image](https://user-images.githubusercontent.com/17100634/236674441-ee1e1886-8ff2-43c6-9d73-72af17d51ae2.png)
